stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\titanic.csv
    deps:
    - .\data\raw\titanic.csv
    - .\src\data\make_dataset.py
    params:
    - make_dataset.test_split
    - make_dataset.seed
    outs:
    - .\data\processed\make_dataset_output\  # Separate directory for make_dataset output

  train_model:
    cmd: python .\src\models\train_model.py .\data\processed\make_dataset_output\
    deps:
    - .\data\processed\make_dataset_output\  # Dependency on the make_dataset output
    - .\src\models\train_model.py
    params:
    - train_model.seed
    - train_model.n_estimators
    - train_model.max_depth
    outs:
    - .\models\train_model_output\  # Separate directory for train_model output

  visualize:
    cmd: python .\src\visualization\visualize.py .\models\model.joblib .\data\processed\make_dataset_output\
    deps:
    - .\data\processed\make_dataset_output\  # Dependency on the make_dataset output
    - .\models\model.joblib
    - .\src\visualization\visualize.py
    outs:
    - dvclive

metrics:
- dvclive\metrics.json

plots:
  - ROC:
      template: simple
      x: fpr
      y:
        dvclive\plots\sklearn\roc\train.json: tpr
        dvclive\plots\sklearn\roc\test.json: tpr
  - Confusion-Matrix:
      template: confusion
      x: actual
      y:
        dvclive\plots\sklearn\cm\train.json: predicted
        dvclive\plots\sklearn\cm\test.json: predicted
  - Precision-Recall:
      template: simple
      x: recall
      y:
        dvclive\plots\sklearn\prc\train.json: precision
        dvclive\plots\sklearn\prc\test.json: precision
